#!/bin/bash
#SBATCH --nodes=1                    # node count
#SBATCH --ntasks=1                   # total number of tasks across all nodes
#SBATCH --cpus-per-task=1            # cpu-cores per task (>1 if multi-threaded tasks), 4 is default
#SBATCH --gpus=1                     # number of gpus per node
#SBATCH --partition=gpu_a100          # partition
#SBATCH --time=00:10:00              # total run time limit (HH:MM:SS)
#SBATCH --output=logs/%x/%j_%x.log   # output file

source .venv/bin/activate
which python
python -c "import sys; print(f'Python version: {sys.version}')"
python -c "import torch; print(f'Torch version: {torch.__version__}, CUDA available: {torch.cuda.is_available()}')"

############################################################

FOLDER=$1

# if FOLDER is not set, exit
if [ -z "$FOLDER" ]; then
  echo "FOLDER is not set. Must specify results folder."
  exit 1
fi

python distorch/compute_metrics.py \
  --pred_folder ${FOLDER}/stitched_pred \
  --ref_folder data/SEGTHOR_CLEAN/val/stitched_gt \
  --pred_extension .nii.gz \
  --ref_extension .nii.gz \
  --num_classes 5 \
  --metrics 3d_dice 3d_hd95 3d_assd \
  --save_folder ${FOLDER}/metrics \
  --overwrite
