#!/bin/bash
#SBATCH --nodes=1                    # node count
#SBATCH --ntasks=1                   # total number of tasks across all nodes
#SBATCH --cpus-per-task=1            # cpu-cores per task (>1 if multi-threaded tasks), 4 is default
#SBATCH --gpus=1                     # number of gpus per node
#SBATCH --partition=gpu_mig          # partition
#SBATCH --time=00:10:00              # total run time limit (HH:MM:SS)
#SBATCH --output=logs/%x/%j_%x.log   # output file

source .venv/bin/activate
which python
python -c "import sys; print(f'Python version: {sys.version}')"
python -c "import torch; print(f'Torch version: {torch.__version__}, CUDA available: {torch.cuda.is_available()}')"

############################################################

make data/TOY2
make data/SEGTHOR
make data/SEGTHOR_CLEAN CFLAGS=-O

# stitch ground truth, needed for 3d metrics
python stitch_regular.py \
  --data_folder data/SEGTHOR_CLEAN/val/gt \
  --dest_folder data/SEGTHOR_CLEAN/val/stitched_gt \
  --num_classes 5 \
  --grp_regex "(Patient_\d\d)_\d\d\d\d" \
  --source_scan_pattern "data/segthor_train/train/{id_}/GT.nii.gz"
