#!/bin/bash
#SBATCH --nodes=1                    # node count
#SBATCH --ntasks=1                   # total number of tasks across all nodes
#SBATCH --cpus-per-task=1            # cpu-cores per task (>1 if multi-threaded tasks), 4 is default
#SBATCH --gpus=1                     # number of gpus per node
#SBATCH --partition=gpu_mig          # partition
#SBATCH --time=00:10:00              # total run time limit (HH:MM:SS)
#SBATCH --output=logs/%x/%j_%x.log   # output file

source .venv/bin/activate
python -c "import sys; print('Python version:', sys.version)"
python -c "import torch; print('Torch version:', torch.__version__); print('CUDA available:', torch.cuda.is_available())"

############################################################

FOLDER=$1

# if FOLDER is not set, exit
if [ -z "$FOLDER" ]; then
  echo "FOLDER is not set. Must specify results folder."
  exit 1
fi

python plot.py --metric_file ${FOLDER}/dice_val.npy --dest ${FOLDER}/dice_val.png
python plot.py --metric_file ${FOLDER}/loss_val.npy --dest ${FOLDER}/loss_val.png
python plot.py --metric_file ${FOLDER}/dice_tra.npy --dest ${FOLDER}/dice_tra.png
python plot.py --metric_file ${FOLDER}/loss_tra.npy --dest ${FOLDER}/loss_tra.png
