#!/bin/bash
#SBATCH --nodes=1                    # node count
#SBATCH --ntasks=1                   # total number of tasks across all nodes
#SBATCH --cpus-per-task=1            # cpu-cores per task (>1 if multi-threaded tasks), 4 is default
#SBATCH --gpus=1                     # number of gpus per node
#SBATCH --partition=gpu_mig          # partition
#SBATCH --time=01:00:00              # total run time limit (HH:MM:SS)
#SBATCH --output=logs/%x/%j_%x.log   # output file

source .venv/bin/activate
python -c "import sys; print('Python version:', sys.version)"
python -c "import torch; print('Torch version:', torch.__version__); print('CUDA available:', torch.cuda.is_available())"

############################################################


RUN_NAME=$1

if [ -z "$RUN_NAME" ]; then
  echo "RUN_NAME argument is not set. Must specify."
  exit 1
fi

FOLDER=${SLURM_JOB_ID}_${RUN_NAME}


# train model
python -O main.py \
  --dataset SEGTHOR_CLEAN \
  --mode full \
  --epoch 1 \
  --dest results/${FOLDER} \
  --gpu \

# stitch predictions
python stitch_v0.py \
  --data_folder results/${FOLDER}/best_epoch/val \
  --dest_folder results/${FOLDER}/stitched_pred \
  --num_classes 5 \
  --grp_regex "(Patient_\d\d)_\d\d\d\d" \
  --source_scan_pattern "data/segthor_train/train/{id_}/GT.nii.gz"

# compute metrics
python distorch/compute_metrics.py \
  --ref_folder results/${FOLDER}/stitched_pred \
  --pred_folder data/SEGTHOR_CLEAN/val/stitched_gt \
  --ref_extension .nii.gz \
  --pred_extension .nii.gz \
  --num_classes 5 \
  --metrics 3d_dice 3d_hd95 \
  --save_folder results/${FOLDER}/metrics

# plot metrics over time
python plot.py --metric_file results/${FOLDER}/dice_val.npy --dest results/${FOLDER}/dice_val.png
python plot.py --metric_file results/${FOLDER}/loss_val.npy --dest results/${FOLDER}/loss_val.png
python plot.py --metric_file results/${FOLDER}/dice_tra.npy --dest results/${FOLDER}/dice_tra.png
python plot.py --metric_file results/${FOLDER}/loss_tra.npy --dest results/${FOLDER}/loss_tra.png
